In [2]:
# We import NumPy into Python
import numpy as np

In [3]:
# We create a 1D ndarray that contains only integers
x = np.array([1,2,3,4,5])
print(x)
print(x.ndim) # returns the number of array dimensions
print(type(x)) # Return the number of array-dimensions (rank), e.g., it will return 2 for a 4x3 array.
print(x.dtype) # tells us the data-type of the elements
print(x.shape) # returns a tuple representing the array dimensions

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
int64
(5,)


In [4]:
# We create a 2D ndarray that contains only integers
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(y)
print(y.ndim)
print(type(y))
print(y.dtype)
print(y.shape)
print(y.size) # Return the number of elements present in the array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
<class 'numpy.ndarray'>
int64
(4, 3)
12


In [5]:
# We create a rank 1 ndarray that contains integers and floats
z=np.array([1,2.5,4])
print(z)
print(z.dtype)
# We create a rank 1 ndarray that contains integers and floats
# but set the dtype to int64
s=np.array([1,2.5,4],dtype=np.int64)
print(s)
print(s.dtype)

[1.  2.5 4. ]
float64
[1 2 4]
int64


### np.load & np.save

In [6]:
np.save('my_array',y)

In [7]:
p = np.load('my_array.npy')
print(p)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### np.zeros(shape)

In [8]:
# We create a 3 x 4 ndarray full of zeros. 
zeros_matrix=np.zeros((3,4))
print(zeros_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### np.ones(shape)

In [9]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))
ones_matrix=np.ones((4,5))
print(ones_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### np.full(shape, constant value)

In [10]:
# We create a 2 x 3 ndarray full of fives. 
fives_matrix=np.full((2,3),5)
print(fives_matrix)

[[5 5 5]
 [5 5 5]]


### np.eye(N)

In [11]:
# We create a 5 x 5 Identity matrix. 
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.diag( values_in_its_main_diagonal)

In [12]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
diagonal_matrix=np.diag((10,20,30,50))
print(diagonal_matrix)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]


### numpy.diag(array, k=0)

In [13]:
# We create a 4 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
# We print the elements in the main diagonal of X
print('z =', np.diag(X))

z = [ 0  6 12 18 24]


In [15]:
# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=1))

y = [ 1  7 13 19]


In [16]:
# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

w =  [ 5 11 17 23]


### np.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)

In [17]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [18]:
# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

The unique elements in X are: [1 2 3 5 8]


### np.arange(start, stop, step, dtype=None)

In [19]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x= np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x= np.arange(4,10) # start is inclusive, stop is exvlusive
print(x)

[4 5 6 7 8 9]


In [21]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x= np.arange(1,14,3)
print(x)

[ 1  4  7 10 13]


### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [22]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
y = np.linspace(0,25,10) # start and stop points are inclusive
print(y)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [23]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
y = np.linspace(0,25,10, endpoint=False) # exluded the end point
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### np.reshape(array, newshape, order='C')

In [24]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)
# We reshape x into a 4 x 5 ndarray 
z = np.reshape(x, (4,5))
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### ndarray.reshape(shape, order='C')

In [25]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
y = np.arange(20).reshape((4,5))
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### np.random.random(shape)

In [26]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
a = np.random.random((3,3))
print(a)

[[0.44546708 0.9690624  0.82992687]
 [0.72456125 0.83604048 0.92418924]
 [0.09589174 0.23864989 0.47091979]]


### np.random.randint(start, stop, size = shape)

In [27]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
b = np.random.randint(4,15,(3,2))
print(b)

[[14  9]
 [ 4 10]
 [12 11]]


### np.random.normal(mean, standard_deviation, size=shape)

In [28]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
c = np.random.normal(0,0.1,size=(1000,1000)) 
print(c)

[[ 1.41888014e-01 -5.73665309e-02 -2.04995230e-01 ...  1.37061799e-01
   1.21913332e-03  1.08939031e-01]
 [ 7.03686727e-02 -1.32622444e-01  7.54241315e-02 ... -5.61293222e-02
  -1.97975585e-02  9.65430825e-03]
 [ 1.06397154e-01  9.66226131e-02  2.41373271e-02 ... -6.91079018e-02
  -1.16105152e-01  1.99913749e-04]
 ...
 [-6.91132714e-02 -1.58454730e-01  1.36591648e-01 ... -3.93138678e-02
  -2.11255354e-01 -1.20530599e-01]
 [-6.15473325e-02  7.38026627e-02 -1.59185167e-01 ...  2.99634563e-02
  -1.34705186e-01 -3.94685762e-02]
 [ 4.95269349e-02  2.52311362e-02 -5.76303540e-02 ... -1.17832416e-01
  -6.24912986e-03 -2.82341326e-02]]


In [29]:
print("mean:",c.mean())
print("stander deviation:",c.std())
print("max:",c.max())
print("min:",c.min())
print("%positive:",(c>0).sum())
print("negative:",(c<0).sum())

mean: 3.6883987780027504e-05
stander deviation: 0.09992291012822828
max: 0.493733460949969
min: -0.4795617075502011
%positive: 500001
negative: 499999


### np.random.permutation(N)
function creates a random permutation of integers from 0 to N-1

In [30]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([4, 3, 1, 0, 2])

### np.delete(ndarray, elements, axis)

In [31]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# We delete the first row of y
w = np.delete(Y, 0, axis=0)
print(w)

[[4 5 6]
 [7 8 9]]


In [33]:
# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)
print(v)

[[2]
 [5]
 [8]]


### np.append(ndarray, elements, axis)

In [34]:
# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


In [35]:
# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10],[11]], axis=1)
print(q)

[[ 1  2  3  9]
 [ 4  5  6 10]
 [ 7  8  9 11]]


### np.insert(ndarray, index, elements, axis)

In [36]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [37]:
# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])
print(x)

[1 2 3 4 5 6 7]


In [38]:
Y = np.array([[1,2,3],[7,8,9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [39]:
# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)
print(w)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)
print(v)

[[1 5 2 3]
 [7 5 8 9]]


### numpy.hstack(sequence_of_ndarray)

In [41]:
# We create a rank 1 ndarray 
x = np.array([1,2])
print("x:",x)
# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])
print("Y:",Y)

x: [1 2]
Y: [[3 4]
 [5 6]]


In [42]:
# We stack x on the right of Y. 
# We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))
print(w)

[[3 4 1]
 [5 6 2]]


### numpy.vstack(sequence_of_ndarray)

In [43]:
# We stack x on top of Y
z = np.vstack((x,Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


### Slicing
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [44]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [45]:
# Method 1
# We select all the elements that are in the 2nd through 4th rows 
# and in the 3rd to 5th columns
Z = X[1:4,2:5]
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [46]:
# Method 2
# We select all the elements that are in the 2nd through 3rd rows
# and in the 3rd through 4rd columns
v = X[2:,3:]
print(v)

[[13 14]
 [18 19]]


In [47]:
# Method 3
# We select all the elements that are in the 1st through 3rd rows
# and in the 1st through 4rd columns
q = X[:3,:4]
print(q)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


### ndarray.copy(order='C')
!!!!!!!! X, Z, v and q are now just different names for the same ndarray. This means that if you make changes in Z or v or q you will be in effect changing the elements in X as well !!!!!!!!

In [48]:
# We change the last element in q to 555
q[2,3] = 555
print(q)
print(X)

[[  0   1   2   3]
 [  5   6   7   8]
 [ 10  11  12 555]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12 555  14]
 [ 15  16  17  18  19]]


=> use : ndarray.copy(order='C')

In [49]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [50]:
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])
print(Z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [51]:
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()
print(W)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [52]:
# We change the last element in W to 444
W[2,2] = 444
print(W)
print(X)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Boolean indexing

In [53]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [54]:
# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


### Set operations :
1. np.intersect1d(ndarry1,ndarry2)
2. np.setdiff1d(ndarry1,ndarry2)
3. np.union1d(ndarry1,ndarry2)

In [55]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])
print(x)
# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])
print(y)

[1 2 3 4 5]
[6 7 2 8 4]


In [56]:
# We use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


### ndarray.sort(axis=-1, kind=None, order=None)

In [57]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))
print(x)

[3 9 4 7 7 2 2 1 5 5]


In [58]:
# We sort x and print the sorted array using sort as a method.
# the original array will be changed to the sorted one
print('Sorted x (out of place):', x.sort())
print(x)

Sorted x (out of place): None
[1 2 2 3 4 5 5 7 7 9]


### np.sort(array, axis=-1, kind=None, order=None)

In [59]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))
print(x)

[8 3 6 5 7 9 4 8 9 2]


In [60]:
# We sort x and print the sorted array using sort as a function.
# It doesn't change the original ndarray being sorted.
print('Sorted x (out of place):', np.sort(x))
print(x)

Sorted x (out of place): [2 3 4 5 6 7 8 8 9 9]
[8 3 6 5 7 9 4 8 9 2]


The axis denotes the axis along which to sort. It can take values in the range -1 to (ndim-1). Axis can take the following possible values for a given 2-D ndarray:

- If nothing is specified, the default value is axis = -1, which sorts along the last axis. In the case of a given 2-D ndarray, the last axis value is 1.
- If explicitly axis = None is specified, the array is flattened before sorting. It will return a 1-D array.
- If axis = 0 is specified for a given 2-D array - For one column at a time, the function will sort all rows, without disturbing other elements. In the final output, you will see that each column has been sorted individually.
- The output of axis = 1 for a given 2-D array is vice-versa for axis = 0. In the final output, you will see that each row has been sorted individually.


In [61]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))
print(X)

[[6 5 3 9 9]
 [7 6 8 2 5]
 [1 8 7 1 3]
 [8 4 1 7 3]
 [8 1 9 9 6]]


In [62]:
# We sort the columns of X and print the sorted array
print('X with sorted columns :\n', np.sort(X, axis = 0))

X with sorted columns :
 [[1 1 1 1 3]
 [6 4 3 2 3]
 [7 5 7 7 5]
 [8 6 8 9 6]
 [8 8 9 9 9]]


In [63]:
# We sort the rows of X and print the sorted array
print('X with sorted rows :\n', np.sort(X, axis = 1))

X with sorted rows :
 [[3 5 6 9 9]
 [2 5 6 7 8]
 [1 1 3 7 8]
 [1 3 4 7 8]
 [1 6 8 9 9]]


## Mathematical functions

In [64]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
print(x)
print(y)

[1 2 3 4]
[5.5 6.5 7.5 8.5]


In [65]:
# We create two rank 2 ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print(X)
print(Y)

[[1 2]
 [3 4]]
[[5.5 6.5]
 [7.5 8.5]]


### Addition

In [66]:
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]


In [67]:
print('X + Y = \n', X + Y)
print('add(X,Y) = \n', np.add(X,Y))

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]
add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]


### Subtraction

In [68]:
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]


In [69]:
print('X - Y = \n', X - Y)
print('subtract(X,Y) = \n', np.subtract(X,Y))

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]


### Multiplication

In [70]:
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]


In [71]:
print('X * Y = \n', X * Y)
print('multiply(X,Y) = \n', np.multiply(X,Y))

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]
multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]


### Division

In [72]:
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


In [73]:
print('X / Y = \n', X / Y)
print('divide(X,Y) = \n', np.divide(X,Y))

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]
divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


### Power

In [74]:
print(np.power(x,2))

[ 1  4  9 16]


In [75]:
print(np.power(X,2))

[[ 1  4]
 [ 9 16]]


### Sqrt

In [76]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [77]:
print(np.sqrt(X))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Exponential

In [78]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [79]:
print(np.exp(X))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


## Statistical functions

In [80]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]
